### ISSUE TITLE
createKeyPairFromPrivateKeyString in KeyPair return type Any

### ISSUE THREAD

**Issue by cfcodefans** [nemtech/nem2-sdk-typescript-javascript#2]
function createKeyPairFromPrivateKeyString(privateKeyString) {
	var privateKey = _convert2.default.hexToUint8(privateKeyString);
	if (Key_Size !== privateKey.length) throw Error('private key has unexpected size: ' + privateKey.length);

	var publicKey = catapult.crypto.extractPublicKey(privateKey, catapult.hash.func);
	return { privateKey: privateKey, publicKey: publicKey };
}

I tried but failed to find a type definition for KeyPair as { privateKey: privateKey, publicKey: publicKey }
This is confusing, since java api does have 
org.nem.core.crypto.KeyPair

**Comment by aleixmorgadas** [comment]
Why do not you use `Account` class instead? The method you are referring is from `nem2-library-js`, which it has the low-level implementations, and because it's JavaScript, it hasn't the type definition.

Check `Account.createFromPrivateKey` [here](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/account/Account.ts#L59-L67).

Java has the `KeyPair` class public, but it should be used the `Account` class too.
