### ISSUE TITLE
How to get txs for an address without pk?

### ISSUE THREAD

**Issue by yaaccount** [nemtech/nem2-sdk-typescript-javascript#250]
There seems to be no way how to get incoming txs if pk is unknown just yet. Consider changing signature of incomingTransactions to (PublicAccount | Address, ...) here https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/b0b308c43edf9bb34b0c0ead7be789319b646895/src/infrastructure/AccountHttp.ts#L273, if api provides it.

**Comment by rg911** [comment]
Hi @yaaccount 
In the coming e3 changes (in PR reviewing), the account transaction endpoints will be using `Address` instead of `PublicKey` as input param. `Address` in the ts sdk can be create by calling either one of the 2 factory methods. 
- `Address.createFromRawAddress` 
- `Address.createFromPublicKey` 

We are simplifying the optional arguments for all endpoints which are using `AccountId (address | pubKey)`

**Comment by rg911** [comment]
Already implemented in v0.13.2
