### ISSUE TITLE
Expose serialization methods

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#56]
The NEM-SDK has a class [TransactionMapping ](https://github.com/nemtech/nem2-sdk-java/blob/450676210c5a75f4624fc3bee7bbde96740109d1/src/main/java/io/nem/sdk/infrastructure/TransactionMapping.java) to map JSON transactions into models.

It can be [useful](https://github.com/nemtech/NIP/issues/6) for advanced users to make use the json mapping, and as well get transactions in serialized form. This table gathers the functions that each transaction model could implement.

<table>
  <tr>
   <td><strong>Function</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>serialize():string
   </td>
   <td>Serializes a transaction model into binary (unsigned payload)
   </td>
  </tr>
  <tr>
   <td>toDTO():json	
   </td>
   <td>Serializes a transaction model into JSON
   </td>
  </tr>
  <tr>
   <td>createFromPayload(data:string):Transaction
   </td>
   <td>Reads the unsigned payload and creates a Transaction.
   </td>
  </tr>
  <tr>
   <td>createFromDTO(data:json):Transaction
   </td>
   <td>Reads from JSON and creates a Transaction.
   </td>
  </tr>
</table>

**Comment by dgarcia360** [comment]
@rg911 Have renamed the name of the functionsto achieve more consistency.

**Comment by evias** [comment]
Merged in master, to be published in v0.11.2

**Comment by aleixmorgadas** [comment]
Hi, [nem2-wallet-browserextension](https://github.com/aleixmorgadas/nem2-wallet-browserextension) has a heavy dependency on this feature, and it's about to be blocked the development since we are reaching the point that we are working with the integration between components.

What prevents to publish `v0.11.2`?

**Comment by rg911** [comment]
> Hi, [nem2-wallet-browserextension](https://github.com/aleixmorgadas/nem2-wallet-browserextension) has a heavy dependency on this feature, and it's about to be blocked the development since we are reaching the point that we are working with the integration between components.
> 
> What prevents to publish `v0.11.2`?

Hi mate, nothing specific, it's all merged. we have got a few tickets done under testing and would like to wrapt them in as well. Let us know if it's blocking your guys.

**Comment by aleixmorgadas** [comment]
I mean, yes, it's blocking us because we need those methods to make it simpler. I don't need that tomorrow, but probably next week.

If I may say, smaller releases with little improvements could work better than waiting for different stuff to be tested and releasing a big piece. I do not have the context of how it's being done now, so ignore this comment in case it's not in the situation of this project ^^

**Comment by evias** [comment]
Ok I will publish a 0.11.2 .

I was actually waiting to also merge work on Fees and Merkle Trees. But currently on this side there is a bug with block info updates..

Will publish a 0.11.2 containing current master changed :+1:
